version: '3'

services:
  typo3-db:
    image: mariadb:latest
    container_name: typo3-db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: typo3
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  typo3-web:
    image: martinhelmich/typo3:11
    container_name: typo3-web
    ports:
      - "80:80"
    links:
      - typo3-db:db
